# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Alexandro E. Treviño"
description: "Research, projects, and writings"
baseurl: # the subpath of your site, e.g. "/blog"
url: "https://alexandrotrevino.github.io"
logo: "/assets/images/bowtie.jpg" # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
  - name: "Source Serif 4"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: atrev_bio

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll/scholar
  - jekyll-remote-theme

# Jekyll-Scholar
scholar:
  style: apa
  source: ./
  bibliography: papers.bib
  sort_by: year,month
  order: descending
  group_by: year
  group_order: descending
  bibliography_template: bibliography_template
  last_name: Trevino
  first_name: Alexandro E

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Google Scholar 
    url: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=z7HDsuAAAAAJ&sortby=pubdate 
    icon: ai ai-google-scholar-square 
  - title: Email 
    url: mailto:alexandro.trevino@gmail.com 
    icon: fa fa-envelope-square 
  - title: GitHub 
    url: https://github.com/alexandrotrevino/ 
    icon: fab fa-github-square 
  - title: Twitter 
    url: https://x.com/atrev_bio 
    icon: fab fa-twitter-square 
  - title: LinkedIn 
    url: https://www.linkedin.com/in/alexandro-trevino-a69ab08b/ 
    icon: fab fa-linkedin
